export const TRACK_POINTS_LIST_AWAIT = "TRACK_POINTS_LIST_AWAIT";
export const TRACK_POINTS_LIST_ERROR = "TRACK_POINTS_LIST_ERROR";
export const TRACK_POINTS_LIST_SUCCESS = "TRACK_POINTS_LIST_SUCCESS";